### ISSUE TITLE
Vertaisarvio1

### ISSUE THREAD

**Issue by heliparv** [xelmas/movie-tracker#1]
Oikein mainiolta vaikuttava ohjelma, siitä tulee varmasti oikein hieno!

Koodi on erittäin siistiä, hyvin jaoteltu luokkiin ja funktioihin, enkä havainnut päällekäisyyksiä. Muuttujat on nimetty riittävän lyhyesti ja kuvaavasti.

Käyttöohje toimii hyvin, mutta laittaisin vielä esimerkkimuodon minkälainen tietokannan osoitteen tulisi olla, eli DATABASE_URL= "postgresql:///[käyttäjänimi]"

En päässyt testailemaan sovelluksen toimintaa sen enempää, koska vaikuttaisi siltä, etten onnistunut saamaan yhteyttä tietokantaan että pääsisin kirjautumaan. Vika on todennäköisesti omassa päässä.

Virheviestit voisivat olla kuvaavia ja niitä voisi olla kattavammin, esimerkiksi virheviesti jos yrittää kirjautua olemattomalla tunnuksella. Jos tunnuksen luominen ei onnistu, voisi mahdollisuuksien mukaan siitä tulla kuvaava viesti. Muutenkin jos jaksaa niin oikeastaan kaikkien mahdollisten operaatioiden yhteyteen olisi plussaa virheviesti, vielä ne näkyivät puuttuvan.

Muuten näyttäisi siltä, että ohjelma on melkein valmis graafista ulkoasua ja paria READMEssa mainittua ominaisuutta lukuunottamatta, hyvää työtä!

**Comment by xelmas** [comment]
Harmi, että et päässyt testailemaan sovellusta. Kiitos kuitenkin hyvistä vinkeistä!
