### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by otsokarhu** [xelmas/movie-tracker#2]
Oikeen hyvältä vaikuttaa! Muutamia parannuskohteita tosin löytyi:
-ulkoasua voi vielä tyylitellä lisää, kuten olitkin jo maininnut
-voisi lisätä sivun, josta näkee kaikki tietokannassa olevat elokuvat ja sarjat
-'mark as watched' ja 'mark to remove' vähän hassuja, voisi muuttaa ihan normi buttoneiksi, nykyisessä ongelmana ainakin se, jos laittaa molempiin bokseihin raksin, ei elokuva siirry katsottujen joukkoon.
-voisi lisätä ominaisuuden, että elokuvan tai sarjan pystyy lisäämään katsottuihin suoraan hausta, ilman että sitä tarvitsee ensin lisätä watchlistille

**Comment by xelmas** [comment]
Hyviä pointteja, kiitos!
